public class MethodsPerClassTest {
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
    public void method1(){}
}
